/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateProfileRequest } from '../../models/update-profile-request';
import { UserProfileResponse } from '../../models/user-profile-response';

export interface UpdateProfile$Params {
      body: UpdateProfileRequest
}

export function updateProfile(http: HttpClient, rootUrl: string, params: UpdateProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<UserProfileResponse>> {
  const rb = new RequestBuilder(rootUrl, updateProfile.PATH, 'patch');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserProfileResponse>;
    })
  );
}

updateProfile.PATH = '/users/profile';
