/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AdminStatsResponse } from './models/admin-stats-response';
export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { BookRequest } from './models/book-request';
export type { BookResponse } from './models/book-response';
export type { BorrowedBookResponse } from './models/borrowed-book-response';
export type { ChangePasswordRequest } from './models/change-password-request';
export type { FeedbackRequest } from './models/feedback-request';
export type { FeedbackResponse } from './models/feedback-response';
export type { PageResponseBookResponse } from './models/page-response-book-response';
export type { PageResponseBorrowedBookResponse } from './models/page-response-borrowed-book-response';
export type { PageResponseFeedbackResponse } from './models/page-response-feedback-response';
export type { PageResponseUserProfileResponse } from './models/page-response-user-profile-response';
export type { RegistrationRequest } from './models/registration-request';
export type { UpdateProfileRequest } from './models/update-profile-request';
export type { UserProfileResponse } from './models/user-profile-response';
