/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserProfileResponse } from '../models/user-profile-response';
export interface PageResponseUserProfileResponse {
  content?: Array<UserProfileResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
