/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserProfile {
  accountLocked?: boolean;
  email?: string;
  firstname?: string;
  id?: number;
  lastname?: string;
}
