/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserProfileResponse {
  dateOfBirth?: string;
  email?: string;
  firstname?: string;
  id?: number;
  lastname?: string;
}
